### ISSUE TITLE
Document Advocate Role

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/agile-task-force#13]
### Description

We've collected some questions around the advocate role:

- What are this persons roles & responsibilities?
- What is the lifecycle of an advocate?
   - How do they get assigned to a team?
   - How do we remove them from a team/move them to a new team?
- Can I make an advocate order me a pizza?

**Comment by ejregithub** [comment]
@bensternthal - does this role persist at all or can we close this issue out as invalid (because it does not)?

**Comment by bensternthal** [comment]
Good point. I think this role is no more at least how it was originally described.
