### ISSUE TITLE
Creating empty list of things (brainstorming doc)

### ISSUE THREAD

**Issue by ejregithub** [mozmeao/agile-task-force#19]
- [x] Create [the document](https://docs.google.com/document/d/1MBPCpQ5uLZ4I4QqC7IlEci-AMmdRTN3mrEX0qYi4jfI/edit?usp=sharing) and share with the team to fill in

Planning what we do the after training, the week after, the next months.
- Document what we want to develop after the training.

**Comment by JennyDouglas** [comment]
here is the brainstorming doc:
https://docs.google.com/document/d/1MBPCpQ5uLZ4I4QqC7IlEci-AMmdRTN3mrEX0qYi4jfI/edit?usp=sharing
