### ISSUE TITLE
Develop Set of Metrics We Want to Impact

### ISSUE THREAD

**Issue by bensternthal** [mozmeao/agile-task-force#6]
## Notes from training
1.  Usage stats from gh / trello

###

We think it would be beneficial to have some number of metrics that we can look at to gauge the effectiveness of our Agile system and to be able to measure the impact of the Agile Task Force.

### Notes from Ben & Alex Brainstorm

Durable Team Board
* Cycle Time & Lead Time: Predictability
* Non-Kanban: Stories over time.
* Usage: Is it helping the team.

Backlog
* Size over time -- noodle 

User Stories
* Level of comfort.
* Qualitative understandability by team.
* Sized and specific enough.
* Completed work matches user story/fulfills user story. (Quality of acceptance criteria).

Daily Standup
* Completed on time
* Attendance
* What makes a productive standup.
* Why is this perceived as not important for some folks. 
* Blockers.
* Rotate who runs this?

3 Week Sprints
* Research this one a bit more. 

Sprint Planning 
* Prioritization etc.
* How efficient(define this) is this long process.

### Thoughts From Training
* Document Waste (Cruft)
* Things used on a daily basis (documents / tools etc)
* Number of meetings

**Comment by ejregithub** [comment]
#26 probably depends on this.
